### ISSUE TITLE
Cannot install aderyn 

### ISSUE THREAD

**Issue by samtdomi** [Cyfrin/aderyn#143]
I have successfully installed rust and cargo - I get verification for both when running "--version" for each. However, I cannot successfully install aderyn - I keep getting these errors in the command line when running ''' cargo install aderyn '''

'''
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `rayon-core` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `serde` (build script) due to previous error
error: could not compile `crossbeam-utils` (build script) due to previous error
error: could not compile `proc-macro2` (build script) due to previous error
error: failed to compile `aderyn v0.0.12`, intermediate artifacts can be found at `/tmp/cargo-installg4LkPc`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
'''

Any help is much appreciated.

**Comment by TilakMaddy** [comment]
Hmm.. I think this has less to do with `aderyn`.  Can you try to maybe compile a simple Hello World Program in rust?

Because if that fails then it's indicative of the linker not being found in your system (which I am assuming you are inside a linux env) 

You could maybe try `sudo apt install build-essential`

More explanation can be found here - https://stackoverflow.com/questions/52445961/how-do-i-fix-the-rust-error-linker-cc-not-found-for-debian-on-windows-10

Hope it help : )

**Comment by alexroan** [comment]
Closing due to staleness
