### ISSUE TITLE
Discussion: Expand the definition of a detector

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#146]
Currently, the definition of a detector is a piece of code that finds and stores issues and makes them available to the report writer.

Following a discussion with [Chase](https://twitter.com/ChaseTheLight99), this idea is to broaden that definition so that detectors are reusable and can do more granular, repeatable things without printing the results to a report.

For example, a detector could be written solely to find all instances where a state variable was altered (feed it a state variable VariableDeclaration and find all Assignments with it on the leftHandSide). This detector would be called by other detectors rather than by the aderyn driver, so it would not produce items for the report.

We could implement this sort of reusable feature in the `browser` package, which currently hosts the Extractor and Parent builtin functionality. However, that locks detector developers into only the functionality in the core code. Now that we have the `nyth` development framework available, it would be great if we could leverage the existing concepts (detectors) and tooling to produce the same outcome, enabling developers to create their own "builtins" whilst they work on their reporting detectors.

There aren't a huge amount of changes to achieve this. The ones that come to mind are:
* Change `found_instances` to have a value of NodeId (i64), change macro
* Add an extra parameter to `Detector.detect` for reusable purposes, ignore for normal detectors?
* Unkown unknowns (I'll look into these ASAP)

The other options are:
* Introduce a new concept, separate from `detectors`, that covers this. Add the new concept to `nyth` with a new command and teach what it's for.
* Continue to build out the built-ins (Extractors) without any of this stuff. (<- This is not really an option if we want to leverage the community to rapidly write useful detectors, IMO).

cc: @TilakMaddy

**Comment by TilakMaddy** [comment]
Off the top of my head (not describing a solution yet)
.
.
.

Bot writers would have more of an interest in creating the bot that works to produce results. Not necessarily maintaining coding best practices and ensuring scalability via reusable components.


This can imply the following

a) they may not even use even the extractxx or getparentxx in the first place. (They may just manually do it )

Surely we can recommend not denying that...

b) coming to your first set of points - yes i think it's good to encourage bot writers to creating more code structures like let's say a helper detector that has a detect function where instances() will only yield the node ID rather than the whole line number thing and stuff...and we can leverage nyth to do that ...when it comes to formalizing it in aderyn we can see where it best fits in the browser package and update docs

**Comment by TilakMaddy** [comment]
Second thoughts 
------------------

In ReactJS, we have class components and function components (maybe class isn't very popular now but eh just for the sake of drawing a parallel)

So similarly, for detector helpers, we can encourage use of something like `struct GetAllEventsEmittedByFunction` which has a `detect(loader: &ContextLoader, func FunctionDefinition)` method that can set `found_instances` to all the node IDs of events emitted by function `func`  and then we return that

AND

we could also encourage the use of a single function `get_all_events_emitted_by_function(loader: &ContextLoader, fn: FunctionDefinition) -> EventDefinition` (which can be used for less complex helper detectors)

**Comment by TilakMaddy** [comment]
In either case, I am not sure how much we should be involved in enforcing a standard -because one of the reasons why react took off for solo projects so much was speed and less restrictions than angular

Note - I am not totally against enforcing a rule; we should just make it is still flexible for people to use and abuse

**Comment by TilakMaddy** [comment]
In regards to definition of the detector - there's one more thing I'd like to add in the near future (not promising tho :P )

Detector is something that reports not just to markdown and json printers, but also to the "Accuracy meter" which is a persistent database - that can help printers "tag" issues for re checking after the report is created based on the how well the detector has performed in the past

This style will be called LightChaserMeter or something like that purely bevause I'd be borrowing the whole concept from ChaseTheLight 's tweets .


He has a whole architecture series that's worth checking out . It's superb ( He was also kind enough to answer my doubts)

**Comment by ChaseTheLight01** [comment]
I'm happy to share how I implemented this feature into lightChaser, perhaps that could help :) 

1) Every detector by default returns an array of found instances. 
2) Report creation only happens once all detectors selected has been run.
3) Detectors can take in two optional inputs
- Objects in scope (what to search in)
- Objects to look for (what to search with)
4) The objects in scope field can be populated with another detector. A example is lets say you want to look for 'for loops in external/public functions'. You can split this into two detectors. One that returns all public and external functions lets call this Detector A. One that looks for a for loop in the function body lets call this Detector B.
5) When defining detector B we can populate the optional scope field with Detector A so detector B which looks for for loops will ONLY look in functions that are external or public. 
6) This is a very simple example but with this tech you can endlessly 'daisychain' detectors and make very complex detectors a lot easier to make. Less chaos in each detector haha.

1) The objects to look with field operated very similarly, this field is also populated with another detector but rather than using the array of found instances as the scope for the child detector, they are used to create the search terms.
2) Lets say you want to look for instances where a address state variable is assigned without a address(0) check. This example will utilize all features.
- Detector A: A detector which returns all setter functions (admin only, set/update/change in it's name) - simplified...
- Detector B: A detector which returns the names of all non constant/immutable address state variables
- Detector C: A detector which returns all functions where a XYZ is assigned and there are no checks against address(0) in the function

Detector C takes detector A as it's scope and detector B to populate it's search terms. In python this is pretty easy to do

1) Search for address(0) checks: == address(0), != address(0) etc...
2) Search for ' XYZ = ' where XYZ is a string from the array provided by detector B. You can use a for loop to look for them all. You can do this with both Regex or AST.

If both 1 and 2 are true, the function gets added to the found instances. Again this is simplified but shows how this feature works.

I hope this helps. I'll make this into a architecture tweet, I may also make make some diagrams to help explain it better :)

**Comment by alexroan** [comment]
> Detectors can take in two optional inputs
> * Objects in scope (what to search in)
> * Objects to look for (what to search with)

Ooo this is epic. OK, so I see two ways we can approach this:

1. Add optional params to `Detector::detect()`
2. Have detector structs include these fields, and use a constructor method like `::with(...,...)` to build the struct

I'm going to write up two PRs and we can discuss the pros and cons once we have the code examples.

**Comment by alexroan** [comment]
Closed in #150 ! 🥳 

Thank you so much @TilakMaddy and @ChaseTheLight01, for your input here. This is an excellent addition to Aderyn!
