### ISSUE TITLE
Using ERC721::_mint() can be dangerous

### ISSUE THREAD

**Issue by allwin199** [Cyfrin/aderyn#165]
I am following @PatrickAlphaC security course. 

In `T-Swap` `ERC20` tokens are used not `ERC721`
while running `aderyn` It outputs the following Issue.

```js
# Medium Issues

## M-1: Using `ERC721::_mint()` can be dangerous

Using `ERC721::_mint()` can mint ERC721 tokens to addresses which don't support ERC721 tokens. Use `_safeMint()` instead of `_mint()` for ERC721.

- Found in src/TSwapPool.sol [Line: 155](src/TSwapPool.sol#L155)

	```solidity
	        _mint(msg.sender, liquidityTokensToMint);
	```
```

I think I am using the latest version. Let me know if I have to update anything.

**Comment by TilakMaddy** [comment]
Hey @allwin199 :P  so that you know, detectors are not 100% accurate in their findings. This is not to say what you are saying is invalid or anything like that - definitely, the said detector can be improved to restrict this only for contracts that inherit IERC20xxx! Very soon ... 🤞 you will be taught how to write your own. And I would love for you to make a much better detector than what we have : )

**Comment by allwin199** [comment]
@TilakMaddy I get your point.

I am excited to learn how to build a detector like this. After learning I would contribute to `aderyn`.

cheers :)
