### ISSUE TITLE
error: unexpected argument '--ast' found

### ISSUE THREAD

**Issue by RensR** [Cyfrin/aderyn#265]
Error `unexpected argument '--ast' found` when running aderyn without any modificatons or arguments. Fresh install of aderyn 0.0.18

```
➜  contracts git:(golf) ✗ aderyn                     
Detecting framework...
Framework detected: Foundry mode engaged.
Foundry root path: "."
error: unexpected argument '--ast' found
```

**Comment by TilakMaddy** [comment]
Please run `foundryup`

**Comment by RensR** [comment]
This error appears to be resolved in later versions of Foundry. Sadly, I cannot always run the latest due to Foundry's non-existent version management. Latest will be purged after a few days, and to maintain consistent results between CI and local we have it set to a frozen version which we update periodically. Do you know what the minimum Foundry version is, then I can update us to some long lives version after that point (if it even exists)

**Comment by TilakMaddy** [comment]
It was introduced here https://github.com/foundry-rs/foundry/pull/7197

**Comment by TilakMaddy** [comment]
I think this is the minimum version https://github.com/foundry-rs/foundry/releases/tag/nightly-de33b6af53005037b463318d2628b5cfcaf39916

**Comment by TilakMaddy** [comment]
@RensR  you could also set `ADERYN_SKIP_BUILD=1` in env . Then `aderyn` will assume that the `out` folder with all the AST json files are ready so it will skip running the forge command.

(But I don't think it is going to help you yet because all the foundry profile stuff is not in place as things like `out` folder are still the defaults)
