### ISSUE TITLE
CFG wanted

### ISSUE THREAD

**Issue by jf-li00** [Cyfrin/aderyn#332]
**Is your feature request related to a problem? Please describe.**
I've seen some of your detector ideas and found that many of them need a Control Flow Graph(CFG) to make the detector easier and more precise.
For example, the `Missing Event` detector needs to check the stroage write opeartion and  the corresponding event emit operation. This would be done easily if we know these two opreations are in the same `Basic Block`.
Another example is the `Weak Randomness` detector. We may need taint analysis for some blockchain states and CFG would help a lot.

**Describe the solution you'd like**
Construct CFG from the AST and implement some detection on CFG.

**Describe alternatives you've considered**
I did't have any better alternatives since it's almost the best way to describe control flow realations of statements.

**Additional context**
No additional context.

**Comment by TilakMaddy** [comment]
Hi there ! 

From my side I propose that if you want to check if two nodes are in the same block - make use of `closest_parent_of_type(block)` API that we have : )

**Comment by TilakMaddy** [comment]
Could you give me an example CFG and a problem that is solved here ? I'm curious to learn about them

**Comment by jf-li00** [comment]
> Could you give me an example CFG and a problem that is solves here ? I'm curious to learn about them

A CFG consists of `basic block`s. CFG is like a tree and basic blocks are nodes. A basic block is a sequence of code without any jump or branch, which means once we get to the first instruction in the basic block, all instructions in the basic block will be executed in a row.

For example, I've write a simple contract missing some event in certain conditions:
![image](https://github.com/Cyfrin/aderyn/assets/106055265/df01c2c3-de09-469d-8bc8-649c65f77982)
And this is part of the CFG(of bytecodes):
![image](https://github.com/Cyfrin/aderyn/assets/106055265/023ec5f1-4255-4aba-95eb-a06d2bc22ca7)
In the above example, the left basic block cotains both the `sstore` and `log`(emit event) operation, if we check again all the updated storage is logged in the `log`, then there is no concern about missing event.
How ever in the right basic block, we could see that there is only a `sstore` and no `emit`, so  `missing event`  may happen.
For the specific condition where `missing event` may happen, please see the parent block of the two `sstire` blocks and we could see the comparison of the parameter.

**Comment by jf-li00** [comment]
> closest_parent_of_type

As for the `closest_parent_of_type(block)` API, it seems that this API gives a `Node` of `AST`, which, in many cases, is way too complex for some static analysis.
For example, in the abovementioned contract, there would be so many `AST Node`s but just a few `basic blocks`.  
:D

**Comment by alexroan** [comment]
Hey @jf-li00, thank you so much for contributing to the conversation here. It is very appreciated!

I totally agree that introducing a CFG would help reduce the complexity of a lot of detectors. I think we're slowly working towards something that looks similar to a CFG but without a preprocessing step.

Some more context about how we're thinking:
The priorities that we've set for Aderyn are two-fold:
1. Accuracy (low false positives, high true positives)
2. Performance

The initial versions of Aderyn started using bare-bones AST, where the detectors themselves had to navigate between nodes. It was actually impossible to traverse _up_ the tree just a few months ago (we didn't have the `browser` module then). Adding the browser module as logical abstractions that act on the bare-bones AST has helped reduce the complexity of detectors, but it is still quite complex.

There is currently just 1 traversal of the AST upon loading into memory, and ideally we want to keep it this way. The reason for this approach is performance. Building a CFG up-front like this can severely impact performance on larger codebases. The fewer pre-processing steps, the more performant Aderyn can be, to the point where it is near-instant on many modern dev machines. 

The challenge that we've set out is to build abstractions, like the browser module with the example you used (~`closest_parent_of_type `~`closest_ancestor_of_type`), to act as building blocks of logic on top of each other, that act on the AST nodes themselves, after a single traversal of the tree. This is instead of front-loading the work in pre-processing steps (traversing the tree more than once, each time trying to build more context, before running the detectors).

As we slowly introduce more logical abstractions that detectors can use, we should approach what _feels_ like a CFG, but without the shortcut of preprocessing it.

I hope that makes sense, and please correct any assumptions I have here. If you think there's a better way to do this, I encourage you to push back! We want to make this the best tool out there :)

Thanks again!

**Comment by jf-li00** [comment]
Hi @alexroan , thanks for you reply.
I totally understand your concern and about performance since smart contracts are being large these days. Building and traversing CFG frequently may introduce much more extra cost.
I am not very familiar with your abstractions on `AST` but after your introduction it makes more sense to me XD
I'll try to understand your detectors that way
