### ISSUE TITLE
Bug: duplicate node ids for different contract

### ISSUE THREAD

**Issue by jf-li00** [Cyfrin/aderyn#370]
**Describe the bug**
In some project, the id of nodes across multiple smart contracts may duplicate and cause some error.

**To Reproduce**
1. Clone this repo: https://github.com/smartcontractkit/ccip/tree/ccip-develop/contracts
2. Run `forge build` and see output in `forge-artifacts`

**Expected behavior**

**Screenshots**
in `ccip/contracts/foundry-artifacts/VRFLoadTestExternalSubOwner.sol/VRFLoadTestExternalSubOwner.json`
![image](https://github.com/Cyfrin/aderyn/assets/106055265/cff42202-dc68-46ae-92b7-ff2cd0a201cd)

in `ccip/contracts/foundry-artifacts/OptimismSequencerUptimeFeed.sol/OptimismSequencerUptimeFeed.0.8.19.json`
![image](https://github.com/Cyfrin/aderyn/assets/106055265/dad330fb-c962-40f6-9507-e292690f134c)

**Comment by jf-li00** [comment]
maybe related to #369

**Comment by jf-li00** [comment]
Since the  `nodes` field of `WorkspaceContext` struct is of `HashMap<NodeID, ASTNode>`, duplicate node ids may cause big trouble.

**Comment by jf-li00** [comment]
Seems solc don't promise that node ids won;t duplicate 😂

**Comment by TilakMaddy** [comment]
Yes, the nodes ids are not unqiue. More context here https://github.com/Cyfrin/aderyn/pull/219

**Comment by alexroan** [comment]
If you run `forge clean` and then try again, do you get the same issue?

**Comment by jf-li00** [comment]
Strange......but when I run `forge clean` and `forge build --ast`, the abovementioned node ids changed and no conflic exists.....

**Comment by alexroan** [comment]
Yep, this is because there were lingering output files from a previously compiled version of a contract. 

Since that previous compilation, something changed (solidity pragma, latest solc version available, etc), so a new output file is created, leaving the old one in place and "stale". Forge doesn't clean these files up, so they linger and annoyingly conflict with newer output files. 

We're working on an internal compilation framework right now which will hopefully resolve these issues.

**Comment by alexroan** [comment]
This is resolved with the coming 0.1.0 release 👀 #489
