### ISSUE TITLE
Aderyn breaks for older solidity versions and blocks running

### ISSUE THREAD

**Issue by satyasai69** [Cyfrin/aderyn#495]
aderyn .        
Root: "/Users/satyasaichava/flashloan", Src: Some(["src"]), Include: None, Exclude: Some(["test/", "script/", "lib/"])
Resolving sources versions by graph ...
Compiling 1 files with Solc 0.5.16+commit.9c3226ce.Darwin.appleclang
Compiling 33 files with Solc 0.8.24+commit.e11b9ed9.Darwin.appleclang
thread '<unnamed>' panicked at /Users/satyasaichava/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aderyn_driver-0.1.0/src/process_auto.rs:149:82:
called `Result::unwrap()` on an `Err` value: Error("EOF while parsing an object", line: 1, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by TilakMaddy** [comment]
Thanks for reaching out!  Looks like old solidity versions like `0.5.*` are not supported in the current architecture.

Is it possible that you can change all the pragma versions to `0.8.*` and try again?

Let us know : )

**Comment by TilakMaddy** [comment]
cc : @alexroan 

There is at least 1 AST in the output that doesn't quite deserialize into `SourceUnit` my guess here is that since we have tried many `0.8.*` repos, it could be that `0.5.*` repo's AST is causing a problem

We need to verify


Following is the breaking line
https://github.com/Cyfrin/aderyn/blob/1de263b55ce91d411987c2b86431b3bf4520b07a/aderyn_driver/src/process_auto.rs#L149

**Comment by alexroan** [comment]
@satyasai69

Are you able to supply the repo or exact set of contracts that this is failing on?
