### ISSUE TITLE
Solc v0.4.x on linux arm64: `SVMError(UnknownVersion) at process_auto.rs:50`

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/aderyn#516]
Using the tests/adhoc-sol-files/multiple-versions/0.4/

**Comment by TilakMaddy** [comment]
This is a known one. 

`foundry-compilers` in our ICF depends on [svm](https://docs.rs/svm-rs/0.5.4/svm/index.html)  (that's why see references like `SolcCompiler` which expands to Solidity Compiler Compiler, go figure :P) for downloading and installing solc binaries

The min version for running 
`const LINUX_AARCH64_MIN: Version = Version::new(0, 5, 0);`

which you can see is defined at https://docs.rs/svm-rs/0.5.4/src/svm/releases.rs.html#32
